# Generated by Django 6.0.7 on 2026-07-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('target_phone_number', models.CharField(max_length=20)),
                ('fraud_type', models.CharField(default='WhatsApp Takeover', max_length=100)),
                ('description', models.TextField()),
                ('amount_lost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
